# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12-alpine

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
        - apk update && apk upgrade && apk add git
        - yarn install
        - yarn lint
        - yarn build:version_json
        - yarn build
