kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: web
        image: ${CICD_REGISTRY}/web:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}-gavle
        ports:
        - containerPort: 80
